### ISSUE TITLE
Install youtupi on non-pi(x86) computer?

### ISSUE THREAD

**Issue by johnwmail** [kktuax/youtupi#27]
Hi, is it possible install youtupi on amd64/linux?
Thanks.

**Comment by kktuax** [comment]
Yes it's possible to install in non pi computers, using VLC instead of omxplayer. I've used this configuration during development.

Regarding the error, looks like it's missing a submodule. Did you install them with:


git submodule init 
git submodule update

**Comment by johnwmail** [comment]
root@dmz132:~/youtupi# git submodule init
Submodule 'pafy' (https://github.com/np1/pafy.git) registered for path 'pafy'
Submodule 'periscope' (git://github.com/kktuax/periscope.git) registered for path 'periscope'
Submodule 'vlc' (https://github.com/geoffsalmon/vlc-python.git) registered for path 'vlc'

root@dmz132:~/youtupi# git submodule update
Cloning into '/root/youtupi/pafy'...
Username for 'https://github.com':

what is username / password? why need that?
any my python version is : 
Python 2.7.15+ (default, Nov 28 2018, 16:27:22) 
[GCC 8.2.0] on linux2

**Comment by orithena** [comment]
The problem is that MS took over github, which prompted the pafy dev to leave github.

We need a new source for that submodule. It's on pypi (i.e. available via pip), but I'm getting other errors when it's not installed as a submodule. @kktuax, did you some on-the-fly patching in there?

**Comment by kktuax** [comment]
I didn't change anything in pafy but I'm using the API in this file:

https://github.com/kktuax/youtupi/blob/a0d8eb04f58c70413c3022185315ed878a6f8531/youtupi/modules/youtube.py

I hope they didn't change the API. @orithena What error do you get? Maybe it's just complaining that the folder is not there, that would be easy to fix in:

https://github.com/kktuax/youtupi/blob/a0d8eb04f58c70413c3022185315ed878a6f8531/youtupi/util/config.py

**Comment by johnwmail** [comment]
Yes, It work
rmdir pafy; ln -s /usr/local/lib/python2.7/dist-packages/pafy
pafy -> /usr/local/lib/python2.7/dist-packages/pafy

**Comment by johnwmail** [comment]
Oh, I mis-understand what youtupi does, (sorry to say that)

I am looking for webui youtube proxy script, 
I want listen youtube on android, and no video transmits( to my mobile),
only audio (my mobile/4G plan has limit) , and tune off the screen while listening it.
do you see something like this?

**Comment by orithena** [comment]
@kktuax yeah, something something about folders sounds about right. (I tried to reinstall youtupi on a new Pi recently and had very little time, so I suspended my efforts to get it running at that point. Didn't even had time to open an issue. Let's discuss this in a new issue with the correct title ^^)

**Comment by johnwmail** [comment]
@orithena Oh yes, thank you.
